# Generated by Django 4.2.2 on 2023-06-14 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('morning', models.BooleanField(default=False)),
                ('noon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('after_food', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('date_of_mfg', models.DateField()),
                ('date_of_expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_personal', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('address_line', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_or_doc', models.BooleanField(default=True)),
                ('datetime_of_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('recorded', models.BooleanField(default=False)),
                ('continuous_fever', models.BooleanField(default=False)),
                ('intermittent_fever', models.BooleanField(default=False)),
                ('shivering', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('body_pain', models.BooleanField(default=False)),
                ('joint_pain', models.BooleanField(default=False)),
                ('weakness', models.BooleanField(default=False)),
                ('cold', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('sneezing', models.BooleanField(default=False)),
                ('throat_pain', models.BooleanField(default=False)),
                ('ear_ache', models.BooleanField(default=False)),
                ('ear_discharge', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('wet_cough', models.BooleanField(default=False)),
                ('breathlessness', models.BooleanField(default=False)),
                ('appetite', models.BooleanField(default=False)),
                ('abdomen_pain', models.BooleanField(default=False)),
                ('loose_motions', models.BooleanField(default=False)),
                ('urine_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.myuser')),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.myuser')),
                ('hypertension_self', models.BooleanField(default=False)),
                ('hypertension_father', models.BooleanField(default=False)),
                ('hypertension_mother', models.BooleanField(default=False)),
                ('diabetes_self', models.BooleanField(default=False)),
                ('diabetes_father', models.BooleanField(default=False)),
                ('diabetes_mother', models.BooleanField(default=False)),
                ('prev_operation_injury', models.CharField(default='nil', max_length=200)),
                ('chronic_disease', models.CharField(default='nil', max_length=200)),
                ('allergic_medicine', models.CharField(default='nil', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.myuser')),
                ('mobile_emergency', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sex', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('staff_or_student', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_eight', to='api.medicine')),
                ('medicine_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_five', to='api.medicine')),
                ('medicine_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_four', to='api.medicine')),
                ('medicine_nine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_nine', to='api.medicine')),
                ('medicine_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_one', to='api.medicine')),
                ('medicine_seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_seven', to='api.medicine')),
                ('medicine_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_six', to='api.medicine')),
                ('medicine_ten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_ten', to='api.medicine')),
                ('medicine_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_three', to='api.medicine')),
                ('medicine_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medicine_two', to='api.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicinemaster'),
        ),
        migrations.CreateModel(
            name='InvestigationTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_eight', to='api.test')),
                ('test_eleven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_eleven', to='api.test')),
                ('test_fifteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_fifteen', to='api.test')),
                ('test_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_five', to='api.test')),
                ('test_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_four', to='api.test')),
                ('test_fourteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_fourteen', to='api.test')),
                ('test_nine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_nine', to='api.test')),
                ('test_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_one', to='api.test')),
                ('test_seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_seven', to='api.test')),
                ('test_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_six', to='api.test')),
                ('test_ten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_ten', to='api.test')),
                ('test_thirteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_thirteen', to='api.test')),
                ('test_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_three', to='api.test')),
                ('test_twelve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_twelve', to='api.test')),
                ('test_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_test_two', to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patient')),
                ('staff_or_relative', models.BooleanField(default=True)),
                ('employee_code', models.CharField(default='nil', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patient')),
                ('course', models.CharField(default='nil', max_length=30)),
                ('admission_num', models.CharField(default='nil', max_length=20)),
                ('hostel_num_and_name', models.CharField(default='nil', max_length=100)),
                ('room_num', models.CharField(default='nil', max_length=5)),
                ('father_occupation', models.CharField(default='nil', max_length=100)),
                ('mother_occupation', models.CharField(default='nil', max_length=100)),
                ('father_mobile', models.CharField(default='nil', max_length=100)),
                ('mother_mobile', models.CharField(default='nil', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('appointment_created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(default='nil', max_length=200)),
                ('diagnosis_duration_days', models.IntegerField(default=0)),
                ('investigation_tests', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investigationtests')),
                ('symptoms', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.symptoms')),
                ('treatment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.treatment')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
