# Generated by Django 4.2.2 on 2023-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='company',
            field=models.CharField(default='nil', max_length=100),
        ),
    ]
