# Generated by Django 4.2.2 on 2023-06-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_id_doctor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='symptoms',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
