# Generated by Django 4.2.2 on 2023-06-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_medicalhistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='user_id',
            new_name='patient_id',
        ),
    ]
