# Generated by Django 4.2.2 on 2023-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicinemaster_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room_num',
            field=models.CharField(default='-1', max_length=5),
        ),
    ]
