# Generated by Django 4.2.2 on 2023-07-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_doctor_id_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_num_and_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_num',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
