# Generated by Django 4.2.2 on 2023-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
