# Generated by Django 4.2.2 on 2023-07-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
    ]
