# Generated by Django 4.2.2 on 2023-07-04 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='recorded',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
