# Generated by Django 4.2.2 on 2023-07-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_symptoms_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='urine_color',
            field=models.CharField(blank=True, default='nil', max_length=50, null=True),
        ),
    ]
